# Generated by Django 3.0.6 on 2020-05-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cowsayinput',
            old_name='text',
            new_name='output_text',
        ),
        migrations.AddField(
            model_name='cowsayinput',
            name='input_text',
            field=models.TextField(default=''),
        ),
    ]
