# Generated by Django 3.0.6 on 2020-05-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0002_auto_20200512_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cowsayinput',
            old_name='input_text',
            new_name='text',
        ),
    ]
